  - repo: git://github.com/bridgecrewio/yor
    rev: 0.1.129
    hooks:
      - id: yor
        name: yor
        entry: yor tag -d
        args: ["."]
        language: golang
        types: [terraform]
        pass_filenames: false
